# Generated by Django 3.2 on 2021-05-03 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requ', '0002_auto_20210503_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='solver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solver', to=settings.AUTH_USER_MODEL),
        ),
    ]
